#!/usr/bin/env bash

set -e

local_binary=$(mktemp --tmpdir -- "build-upload.${1?no package name provided}.XXXXXXXXX")
trap 'rm -f "$local_binary"' EXIT

repo=$(basename $(git rev-parse --show-toplevel))
remote_binary="$repo/$(basename "$1" .go).$USER"

echo "[1/3] Building ${remote_binary}..."
GOOS=linux GOARCH=arm go build -o "$local_binary" "$1"

echo "[2/3] Copying $remote_binary to ${REMOTE_HOST:=pi}..."
scp "$local_binary" ${REMOTE_HOST}:"$remote_binary"

echo "[3/3] Starting $remote_binary at ${REMOTE_HOST}..."
ssh ${REMOTE_HOST} "$remote_binary"
