#!/bin/sh

while :; do
	ssh -vvv \
		-o 'ExitOnForwardFailure yes' \
		-o 'ServerAliveInterval 30' \
		-o 'ConnectTimeout 5' \
		-o 'BatchMode yes' \
		-N -R ${REMOTE_PORT?}:localhost:22 ${REMOTE_HOST?}
	sleep 1
done
